version: '2'

services:
  app:
    image: 'chef-docker:latest'
    ports:
      - 8080:8080
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin