
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.Reader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.json.JSONArray;
import org.json.JSONObject;
import org.omg.CORBA.Request;
import sun.misc.IOUtils;
import sun.net.www.http.HttpClient;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Álvaro
 */
public class Principal extends javax.swing.JFrame {

    private String token = "";

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jPanel_crearCuenta.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_background = new javax.swing.JPanel();
        jLayeredPane_contenedor = new javax.swing.JLayeredPane();
        jPanel_login = new javax.swing.JPanel();
        jButton_login = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel_mensajeLogin = new javax.swing.JLabel();
        jButton_nuevaCuenta = new javax.swing.JButton();
        jPasswordField_password = new javax.swing.JPasswordField();
        jPanel_Usuario = new javax.swing.JPanel();
        jButton_usuario = new javax.swing.JButton();
        jLabel_nombre1 = new javax.swing.JLabel();
        jLabel_apellidos1 = new javax.swing.JLabel();
        jLabel_direccion1 = new javax.swing.JLabel();
        jLabel_codigoPostal1 = new javax.swing.JLabel();
        jLabel_poblacion1 = new javax.swing.JLabel();
        jLabel_nacionalidad1 = new javax.swing.JLabel();
        jLabel_edad1 = new javax.swing.JLabel();
        jLabel_tipoUsuario1 = new javax.swing.JLabel();
        jLabel_nombreUsuario = new javax.swing.JLabel();
        jLabel_apellidosUsuario = new javax.swing.JLabel();
        jLabel_direccionUsuario = new javax.swing.JLabel();
        jLabel_codigoPostalUsuario = new javax.swing.JLabel();
        jLabel_poblacionUsuario = new javax.swing.JLabel();
        jLabel_nacionalidadUsuario = new javax.swing.JLabel();
        jLabel_edadUsuario = new javax.swing.JLabel();
        jLabel_tipoUsuarioUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_telefonoUsuario = new javax.swing.JLabel();
        jLabel_emailUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_usernameUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel_IBANUsuario = new javax.swing.JLabel();
        jPanel_crearCuenta = new javax.swing.JPanel();
        jButton_crearCuenta = new javax.swing.JButton();
        jTextField_nombre = new javax.swing.JTextField();
        jTextField_apellidos = new javax.swing.JTextField();
        jTextField_direccion = new javax.swing.JTextField();
        jTextField_codigoPostal = new javax.swing.JTextField();
        jTextField_poblacion = new javax.swing.JTextField();
        jTextField_nacionalidad = new javax.swing.JTextField();
        jTextField_edad = new javax.swing.JTextField();
        jComboBox_tipoUsuario = new javax.swing.JComboBox<>();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_apellidos = new javax.swing.JLabel();
        jLabel_direccion = new javax.swing.JLabel();
        jLabel_codigoPostal = new javax.swing.JLabel();
        jLabel_poblacion = new javax.swing.JLabel();
        jLabel_nacionalidad = new javax.swing.JLabel();
        jLabel_edad = new javax.swing.JLabel();
        jLabel_tipoUsuario = new javax.swing.JLabel();
        jLabel_telefono = new javax.swing.JLabel();
        jTextField_telefono = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jButton_exit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_contraseña = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_IBAN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton_login.setText("Entrar");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Inserte su usuario y contraseña:");

        jTextField_usuario.setText("Usuario");
        jTextField_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField_usuarioMouseExited(evt);
            }
        });

        jLabel_mensajeLogin.setForeground(new java.awt.Color(255, 51, 51));
        jLabel_mensajeLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton_nuevaCuenta.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jButton_nuevaCuenta.setText("¿No tienes cuenta?, crea una nueva aquí");
        jButton_nuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevaCuentaActionPerformed(evt);
            }
        });

        jPasswordField_password.setText("Contraseña");
        jPasswordField_password.setMinimumSize(new java.awt.Dimension(4, 20));
        jPasswordField_password.setSelectionStart(0);

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel_mensajeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButton_nuevaCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel_mensajeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton_nuevaCuenta))
        );

        jButton_usuario.setText("Salir");
        jButton_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_usuarioActionPerformed(evt);
            }
        });

        jLabel_nombre1.setText("Nombre:");

        jLabel_apellidos1.setText("Apellidos:");

        jLabel_direccion1.setText("Dirección:");

        jLabel_codigoPostal1.setText("Código Postal:");

        jLabel_poblacion1.setText("Población:");

        jLabel_nacionalidad1.setText("Nacionalidad:");

        jLabel_edad1.setText("Edad:");

        jLabel_tipoUsuario1.setText("Tipo de usuario:");

        jLabel_nombreUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_nombreUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_apellidosUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_apellidosUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_direccionUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_direccionUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_codigoPostalUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_codigoPostalUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_poblacionUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_poblacionUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_nacionalidadUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_nacionalidadUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_edadUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_edadUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_tipoUsuarioUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_tipoUsuarioUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel1.setText("Teléfono:");

        jLabel2.setText("Email:");

        jLabel_telefonoUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_telefonoUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel_emailUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_emailUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel3.setText("Nombre de usuario:");

        jLabel_usernameUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_usernameUsuario.setForeground(new java.awt.Color(51, 102, 255));

        jLabel8.setText("IBAN:");

        jLabel_IBANUsuario.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel_IBANUsuario.setForeground(new java.awt.Color(51, 102, 255));

        javax.swing.GroupLayout jPanel_UsuarioLayout = new javax.swing.GroupLayout(jPanel_Usuario);
        jPanel_Usuario.setLayout(jPanel_UsuarioLayout);
        jPanel_UsuarioLayout.setHorizontalGroup(
            jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_UsuarioLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_direccionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_UsuarioLayout.createSequentialGroup()
                        .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_nombre1)
                                    .addComponent(jLabel_codigoPostalUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_direccion1)
                                    .addComponent(jLabel_codigoPostal1)
                                    .addComponent(jLabel_nacionalidad1))
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(95, 95, 95))
                            .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel_telefonoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(34, 34, 34)))
                        .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_IBANUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_emailUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_poblacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel_poblacion1)
                                    .addComponent(jLabel_apellidos1)
                                    .addComponent(jLabel2)
                                    .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                                        .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_edadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_edad1))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_tipoUsuario1)
                                            .addComponent(jLabel_tipoUsuarioUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jButton_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 70, Short.MAX_VALUE))
                            .addComponent(jLabel_apellidosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_UsuarioLayout.createSequentialGroup()
                        .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nacionalidadUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_usernameUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_nombreUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );
        jPanel_UsuarioLayout.setVerticalGroup(
            jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre1)
                    .addComponent(jLabel_apellidos1))
                .addGap(18, 18, 18)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_apellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_direccion1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_direccionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_poblacion1)
                    .addComponent(jLabel_codigoPostal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_codigoPostalUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_UsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel_poblacionUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_edad1)
                    .addComponent(jLabel_nacionalidad1)
                    .addComponent(jLabel_tipoUsuario1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_tipoUsuarioUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel_edadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_nacionalidadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_emailUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(jLabel_telefonoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_IBANUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jLabel_usernameUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton_usuario)
                .addGap(34, 34, 34))
        );

        jPanel_crearCuenta.setEnabled(false);

        jButton_crearCuenta.setText("Crear cuenta");
        jButton_crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crearCuentaActionPerformed(evt);
            }
        });

        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jComboBox_tipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Cliente", "Chef", "Administrador" }));
        jComboBox_tipoUsuario.setToolTipText("");
        jComboBox_tipoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_tipoUsuarioActionPerformed(evt);
            }
        });

        jLabel_nombre.setText("Nombre:");

        jLabel_apellidos.setText("Apellidos:");

        jLabel_direccion.setText("Dirección:");

        jLabel_codigoPostal.setText("Código Postal:");

        jLabel_poblacion.setText("Población:");

        jLabel_nacionalidad.setText("Nacionalidad:");

        jLabel_edad.setText("Edad:");

        jLabel_tipoUsuario.setText("Tipo de usuario:");

        jLabel_telefono.setText("Teléfono:");

        jLabel_email.setText("Email:");

        jButton_exit.setText("Salir");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre de usuario:");

        jLabel6.setText("Contraseña:");

        jLabel7.setText("IBAN");

        javax.swing.GroupLayout jPanel_crearCuentaLayout = new javax.swing.GroupLayout(jPanel_crearCuenta);
        jPanel_crearCuenta.setLayout(jPanel_crearCuentaLayout);
        jPanel_crearCuentaLayout.setHorizontalGroup(
            jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                        .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nacionalidad)
                            .addComponent(jLabel_codigoPostal)
                            .addComponent(jLabel_direccion)
                            .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                                        .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel_nombre))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_apellidos)
                                            .addComponent(jTextField_apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_crearCuentaLayout.createSequentialGroup()
                                    .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_crearCuentaLayout.createSequentialGroup()
                                            .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jTextField_codigoPostal)
                                                .addComponent(jTextField_nacionalidad, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextField_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField_poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel_poblacion)
                                                .addComponent(jLabel_edad)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel_crearCuentaLayout.createSequentialGroup()
                                            .addGap(231, 231, 231)
                                            .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                                                    .addComponent(jLabel_tipoUsuario)
                                                    .addGap(112, 112, 112)
                                                    .addComponent(jLabel_telefono))
                                                .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                                                    .addComponent(jComboBox_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(29, 29, 29)
                                                    .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                                                            .addComponent(jButton_crearCuenta)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(jButton_exit)
                                                            .addGap(43, 43, 43))
                                                        .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                                                            .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel7)
                                                                .addComponent(jTextField_IBAN, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGap(0, 0, Short.MAX_VALUE)))))))
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGap(0, 53, Short.MAX_VALUE))
                    .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                        .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_email)
                            .addComponent(jTextField_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel_crearCuentaLayout.setVerticalGroup(
            jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crearCuentaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jLabel_apellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextField_apellidos))
                .addGap(22, 22, 22)
                .addComponent(jLabel_direccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_codigoPostal)
                    .addComponent(jLabel_poblacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_codigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_poblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nacionalidad)
                    .addComponent(jLabel_edad)
                    .addComponent(jLabel_tipoUsuario)
                    .addComponent(jLabel_telefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_tipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_email)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField_IBAN, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jTextField_contraseña))
                .addGap(27, 27, 27)
                .addGroup(jPanel_crearCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_crearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLayeredPane_contenedor.setLayer(jPanel_login, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane_contenedor.setLayer(jPanel_Usuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane_contenedor.setLayer(jPanel_crearCuenta, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane_contenedorLayout = new javax.swing.GroupLayout(jLayeredPane_contenedor);
        jLayeredPane_contenedor.setLayout(jLayeredPane_contenedorLayout);
        jLayeredPane_contenedorLayout.setHorizontalGroup(
            jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
            .addGroup(jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_contenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_contenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_contenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_crearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane_contenedorLayout.setVerticalGroup(
            jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_contenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_contenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane_contenedorLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel_crearCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout jPanel_backgroundLayout = new javax.swing.GroupLayout(jPanel_background);
        jPanel_background.setLayout(jPanel_backgroundLayout);
        jPanel_backgroundLayout.setHorizontalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 717, Short.MAX_VALUE)
            .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel_backgroundLayout.setVerticalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_backgroundLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLayeredPane_contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        /*Codigo anterior realizado al principio del TEA2 para login con datos hardcodeados
        boolean comprobacion = comprobarLogin(jTextField_usuario.getText(), jPasswordField_password.getPassword());
        if (comprobacion) {
            switchPanels(jPanel_Usuario);
        } else {
            jLabel_mensajeLogin.setText("Error en el usuario o contraseña introducidos");
        }
         */
        //Código para login con conexión a API rest
        //Consulta POST
        try {
            String apiUrl = "http://localhost:8080/api/auth/iniciarSesion"; // api/http link             
            URL url = new URL(apiUrl);
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setDoOutput(true);
            connection.setRequestProperty("Content-Type", "application/json");
            connection.setRequestProperty("Accept", "application/json");
            //connection.setRequestProperty("Authorization", "Basic " + Base64.getEncoder().encodeToString((userName + ":" + password).getBytes()));
            //String payload = "{\"usernameOrEmail\": \"pepe2\", \"password\": \"password\"}";// This should be your json body i.e. {"Name" : "Mohsin"}
            String contraseña = String.valueOf(jPasswordField_password.getPassword());
            String payload = "{\"usernameOrEmail\": \"" + jTextField_usuario.getText() + "\", \"password\": \"" + contraseña + "\"}";
            byte[] out = payload.getBytes(StandardCharsets.UTF_8);
            OutputStream stream = connection.getOutputStream();
            stream.write(out);

            if (connection.getResponseCode() != 200) {
                if (connection.getResponseCode() != 500) {
                    JOptionPane.showMessageDialog(null, "Fallo de conexión con el servidor. Error " + connection.getResponseCode());
                } else {
                    jLabel_mensajeLogin.setText("Error en el usuario o contraseña introducidos");
                }

            } else {

                InputStream response = connection.getInputStream();

                //Leyendo la respuesta de la API
                StringBuilder sb = new StringBuilder();
                BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                String linea;
                while ((linea = in.readLine()) != null) {
                    sb.append(linea).append("\n");
                }
                in.close();
                //Pasando la respuesta a objeto JSON para poder usarla
                JSONArray jsonArray = new JSONArray("[" + sb.toString() + "]");
                JSONObject jsonObject = jsonArray.getJSONObject(0);
                token = jsonObject.getString("tokenDeAcceso");
                //Se limpia un label de error de contraseña y se cambia al panel Usuario
                jLabel_mensajeLogin.setText("");
                switchPanels(jPanel_Usuario);

                // Se realiza una solicitud GET para recibir los datos del usuario
                try {
                    String urlString = "http://localhost:8080/api/users/get/user";
                    urlString = urlString + "?usernameOrEmail=" + jTextField_usuario.getText()
                            + "&password=password"; //+jPasswordField_password.getPassword().toString();

                    apiUrl = urlString; //api/http link                                    
                    url = new URL(apiUrl);
                    connection = (HttpURLConnection) url.openConnection();
                    connection.setRequestMethod("GET");
                    connection.setDoOutput(true);
                    connection.setRequestProperty("Accept", "application/json");
                    connection.setRequestProperty("Authorization", "Bearer " + token);

                    if (connection.getResponseCode() != 200) {
                        JOptionPane.showMessageDialog(null, "Fallo de conexión con el servidor. Error " + connection.getResponseCode());

                    } else {

                        response = connection.getInputStream();
                        //Leyendo la respuesta de la API
                        StringBuilder sb2 = new StringBuilder();
                        in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                        while ((linea = in.readLine()) != null) {
                            sb2.append(linea).append("\n");
                        }
                        in.close();
                        //Pasando la respuesta a objeto JSON para poder usarla
                        jsonObject = new JSONObject(sb2.toString());
                        //Se aplican los valores recibidos a los campos de lpanel Usuarios
                        if (jsonObject.getString("nombre") != null) {
                            jLabel_nombreUsuario.setText(jsonObject.getString("nombre"));
                        }
                        if (jsonObject.get("apellidos") != null) {
                            jLabel_apellidosUsuario.setText(String.valueOf(jsonObject.get("apellidos")));
                        }
                        if (jsonObject.get("direccion") != null) {
                            jLabel_direccionUsuario.setText(String.valueOf(jsonObject.get("direccion")));
                        }
                        if (jsonObject.get("codigoPostal") != null) {
                            jLabel_codigoPostalUsuario.setText(String.valueOf(jsonObject.get("codigoPostal")));
                        }
                        if (jsonObject.get("poblacion") != null) {
                            jLabel_poblacionUsuario.setText(String.valueOf(jsonObject.get("poblacion")));
                        }
                        if (jsonObject.get("nacionalidad") != null) {
                            jLabel_nacionalidadUsuario.setText(String.valueOf(jsonObject.get("nacionalidad")));
                        }
                        if (jsonObject.get("edad") != null) {
                            jLabel_edadUsuario.setText(String.valueOf(jsonObject.get("edad")));
                        }
                        if (jsonObject.get("telefono") != null) {
                            jLabel_telefonoUsuario.setText(String.valueOf(jsonObject.get("telefono")));
                        }
                        if (jsonObject.get("email") != null) {
                            jLabel_emailUsuario.setText(jsonObject.getString("email"));
                        }
                        if (jsonObject.get("username") != null) {
                            jLabel_usernameUsuario.setText(jsonObject.getString("username"));
                        }
                        if (jsonObject.get("iban") != null) {
                            jLabel_IBANUsuario.setText(String.valueOf(jsonObject.get("iban")));
                        }

                        //Asignamos el tipo al ComboBox y lo mostramos en el panel de usuario
                        if (jsonObject.get("roles") != null) {
                            jsonArray = new JSONArray(jsonObject.get("roles").toString());
                            JSONObject jsonObjectRoles = jsonArray.getJSONObject(0);
                            if (jsonObjectRoles.getString("role").equals("ROLE_ADMIN")) {
                                jComboBox_tipoUsuario.setSelectedItem("Administrador");
                                jLabel_tipoUsuarioUsuario.setText(jComboBox_tipoUsuario.getSelectedItem().toString());
                            }
                            if (jsonObjectRoles.getString("role").equals("ROLE_CHEF")) {
                                jComboBox_tipoUsuario.setSelectedItem("Chef");
                                jLabel_tipoUsuarioUsuario.setText(jComboBox_tipoUsuario.getSelectedItem().toString());
                            }
                            if (jsonObjectRoles.getString("role").equals("ROLE_CLIENT")) {
                                jComboBox_tipoUsuario.setSelectedItem("Cliente");
                                jLabel_tipoUsuarioUsuario.setText(jComboBox_tipoUsuario.getSelectedItem().toString());

                            }

                        }
                    }
                    connection.disconnect();

                } catch (MalformedURLException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Error: " + ex);
                }

            }
            connection.disconnect();

        } catch (MalformedURLException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }

    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_usuarioActionPerformed
        // TODO add your handling code here:
        token = "";
        switchPanels(jPanel_login);
    }//GEN-LAST:event_jButton_usuarioActionPerformed

    private void jButton_nuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevaCuentaActionPerformed
        // TODO add your handling code here:
        jPanel_crearCuenta.setEnabled(true);
        jPanel_crearCuenta.setVisible(true);
        switchPanels(jPanel_crearCuenta);
    }//GEN-LAST:event_jButton_nuevaCuentaActionPerformed

    private void jButton_crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crearCuentaActionPerformed
        // TODO add your handling code here:
        //Deben enviarse los datos a la BBDD
        String tipoUsuario = jComboBox_tipoUsuario.getSelectedItem().toString();
        //Se comprueba que el usuario haya introducido datos
        if ((!jTextField_nombre.getText().isEmpty()
                && !jTextField_apellidos.getText().isEmpty() && !jTextField_direccion.getText().isEmpty()
                && !jTextField_codigoPostal.getText().isEmpty() && !jTextField_poblacion.getText().isEmpty()
                && !jTextField_nacionalidad.getText().isEmpty() && !jTextField_edad.getText().isEmpty()
                && !tipoUsuario.isEmpty() && !jTextField_telefono.getText().isEmpty() && !jTextField_email.getText().isEmpty())) {

            //Se aplican los datos introducidos a los label de la ficha de usuario
            jLabel_nombreUsuario.setText(jTextField_nombre.getText());
            jLabel_apellidosUsuario.setText(jTextField_apellidos.getText());
            jLabel_direccionUsuario.setText(jTextField_direccion.getText());
            jLabel_codigoPostalUsuario.setText(jTextField_codigoPostal.getText());
            jLabel_poblacionUsuario.setText(jTextField_poblacion.getText());
            jLabel_nacionalidadUsuario.setText(jTextField_nacionalidad.getText());
            jLabel_edadUsuario.setText(jTextField_edad.getText());
            jLabel_tipoUsuarioUsuario.setText(jComboBox_tipoUsuario.getSelectedItem().toString());
            jLabel_telefonoUsuario.setText(jTextField_telefono.getText());
            jLabel_emailUsuario.setText(jTextField_email.getText());
            jLabel_usernameUsuario.setText(jTextField_username.getText());
            jLabel_IBANUsuario.setText(jTextField_IBAN.getText());

            //Se realiza el POST a la API rest:
            String apiUrl = "http://localhost:8080/api/auth/registrar"; // Your api/http link
            URL url;
            try {
                url = new URL(apiUrl);
                HttpURLConnection connection = (HttpURLConnection) url.openConnection();
                connection.setRequestMethod("POST");
                connection.setDoOutput(true);
                connection.setRequestProperty("Content-Type", "application/json");
                connection.setRequestProperty("Accept", "application/json");
                //connection.setRequestProperty("Authorization", "Bearer " + token);                 
                //String payload = "{\"usernameOrEmail\": \"pepe2\", \"password\": \"password\"}";// This should be your json body i.e. {"Name" : "Mohsin"}
                //Se crea la variable del perfil adecuada (ROLE_) para hacer después el BODY
                String perfil = "";
                if (jComboBox_tipoUsuario.getSelectedItem().toString().equals("Cliente")) {
                    perfil = "ROLE_CLIENT";
                }
                if (jComboBox_tipoUsuario.getSelectedItem().toString().equals("Chef")) {
                    perfil = "ROLE_CHEF";
                }
                if (jComboBox_tipoUsuario.getSelectedItem().toString().equals("Administrador")) {
                    perfil = "ROLE_ADMIN";
                }
                //Se crea el BODY con los valores String de los label del panel Usuario

                String payload = "{\"nombre\": \"" + jTextField_nombre.getText() + "\","
                        + " \"email\": \"" + jTextField_email.getText() + "\","
                        + " \"username\": \"" + jTextField_username.getText() + "\","
                        + " \"password\": \"" + jTextField_contraseña.getText() + "\","
                        + " \"perfil\": \"" + perfil + "\","
                        + " \"apellidos\": \"" + jTextField_apellidos.getText() + "\","
                        + " \"direccion\": \"" + jTextField_direccion.getText() + "\","
                        + " \"codigoPostal\": \"" + jTextField_codigoPostal.getText() + "\","
                        + " \"poblacion\": \"" + jTextField_poblacion.getText() + "\","
                        + " \"nacionalidad\": \"" + jTextField_nacionalidad.getText() + "\","
                        + " \"edad\": \"" + jTextField_edad.getText() + "\","
                        + " \"telefono\": \"" + jTextField_telefono.getText() + "\","
                        + " \"iban\": \"" + jTextField_IBAN.getText() + "\"}";

                byte[] out = payload.getBytes(StandardCharsets.UTF_8);
                OutputStream stream = connection.getOutputStream();
                stream.write(out);
                if (connection.getResponseCode() != 200) {
                    JOptionPane.showMessageDialog(null, "Fallo de conexión con el servidor. Error " + connection.getResponseCode());
                } else {
                    InputStream response = connection.getInputStream();

                    //Leyendo la respuesta de la API
                    StringBuilder sb = new StringBuilder();
                    BufferedReader in = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                    String linea;
                    while ((linea = in.readLine()) != null) {
                        sb.append(linea).append("\n");
                    }
                    in.close();
                    //Se recibe el mensaje de la API conforme se crea o si está duplicado
                    String mensajeRecibido = sb.toString();
                    //Se avisa de la creación de la cuenta al usuario:
                    JOptionPane.showMessageDialog(null, mensajeRecibido);
                    //Se cambia el panel
                    switchPanels(jPanel_Usuario);
                }
                connection.disconnect();

            } catch (MalformedURLException ex) {
                JOptionPane.showMessageDialog(null, "Error en la conexión con el servidor: " + ex);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Error en la conexión con el servidor: " + ex);
            }

        } else {
            //Se avisa al usuario que le faltan introducir datos para crear la cuenta
            JOptionPane.showMessageDialog(null, "Por favor, introduzca los datos necesarios");
        }

    }//GEN-LAST:event_jButton_crearCuentaActionPerformed

    private void jComboBox_tipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_tipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_tipoUsuarioActionPerformed

    private void jTextField_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMouseClicked
        // TODO add your handling code here:
        if (jTextField_usuario.getText().equals("Usuario")) {
            jTextField_usuario.setText("");
        }
    }//GEN-LAST:event_jTextField_usuarioMouseClicked

    private void jTextField_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usuarioMouseExited
        // TODO add your handling code here:
        if (jTextField_usuario.getText().isEmpty()) {
            jTextField_usuario.setText("Usuario");
        }
    }//GEN-LAST:event_jTextField_usuarioMouseExited

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        token = "";
        switchPanels(jPanel_login);
    }//GEN-LAST:event_jButton_exitActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });

    }

    public void switchPanels(JPanel panel) {
        jLayeredPane_contenedor.removeAll();
        jLayeredPane_contenedor.add(panel);
        jLayeredPane_contenedor.repaint();
        jLayeredPane_contenedor.revalidate();
    }

    private boolean comprobarLogin(String userName, char[] password) {
        userName = "Alberto";
        password = new char[]{'1', '2', '3', '4'};
        String correctPassword = String.valueOf(password);
        if (userName.equalsIgnoreCase(jTextField_usuario.getText()) && correctPassword.equals(String.valueOf(jPasswordField_password.getPassword()))) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_crearCuenta;
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_login;
    private javax.swing.JButton jButton_nuevaCuenta;
    private javax.swing.JButton jButton_usuario;
    private javax.swing.JComboBox<String> jComboBox_tipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_IBANUsuario;
    private javax.swing.JLabel jLabel_apellidos;
    private javax.swing.JLabel jLabel_apellidos1;
    private javax.swing.JLabel jLabel_apellidosUsuario;
    private javax.swing.JLabel jLabel_codigoPostal;
    private javax.swing.JLabel jLabel_codigoPostal1;
    private javax.swing.JLabel jLabel_codigoPostalUsuario;
    private javax.swing.JLabel jLabel_direccion;
    private javax.swing.JLabel jLabel_direccion1;
    private javax.swing.JLabel jLabel_direccionUsuario;
    private javax.swing.JLabel jLabel_edad;
    private javax.swing.JLabel jLabel_edad1;
    private javax.swing.JLabel jLabel_edadUsuario;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_emailUsuario;
    private javax.swing.JLabel jLabel_mensajeLogin;
    private javax.swing.JLabel jLabel_nacionalidad;
    private javax.swing.JLabel jLabel_nacionalidad1;
    private javax.swing.JLabel jLabel_nacionalidadUsuario;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_nombre1;
    private javax.swing.JLabel jLabel_nombreUsuario;
    private javax.swing.JLabel jLabel_poblacion;
    private javax.swing.JLabel jLabel_poblacion1;
    private javax.swing.JLabel jLabel_poblacionUsuario;
    private javax.swing.JLabel jLabel_telefono;
    private javax.swing.JLabel jLabel_telefonoUsuario;
    private javax.swing.JLabel jLabel_tipoUsuario;
    private javax.swing.JLabel jLabel_tipoUsuario1;
    private javax.swing.JLabel jLabel_tipoUsuarioUsuario;
    private javax.swing.JLabel jLabel_usernameUsuario;
    private javax.swing.JLayeredPane jLayeredPane_contenedor;
    private javax.swing.JPanel jPanel_Usuario;
    private javax.swing.JPanel jPanel_background;
    private javax.swing.JPanel jPanel_crearCuenta;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_IBAN;
    private javax.swing.JTextField jTextField_apellidos;
    private javax.swing.JTextField jTextField_codigoPostal;
    private javax.swing.JTextField jTextField_contraseña;
    private javax.swing.JTextField jTextField_direccion;
    private javax.swing.JTextField jTextField_edad;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nacionalidad;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_poblacion;
    private javax.swing.JTextField jTextField_telefono;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextField jTextField_usuario;
    // End of variables declaration//GEN-END:variables
}
